---
title: "About EREN"
---

The Educational Research and Evaluation Network (EREN) is a group of educational researchers and evaluators from across Virginia, Maryland, and the District of Columbia. Although primarily comprised of school division staff, EREN regularly collaborates with universities and the Virginia Department of Education (VDOE) in pursuit of our vision and mission.

# Vision

We empower all learners by building capacity for inquiry and continuous improvement across school systems.

# Mission

To cultivate inquiry among educational researchers and evaluators by experimenting with innovative methodologies, maintaining high standards of practice, and sharing knowledge and resources both within and outside of the network.

# Leadership and Committees

## Leadership

**Co-Chairs:** *Phil Riddle and Eric Ekholm*

The EREN co-chairs facilitate monthly Council meetings, represent EREN at state and national conferences, and maintain day-to-day records.  Co-chairs are elected every two years in the spring.

**Past Co-Chairs:** *Rebecca Towery and Chad Green*

EREN past co-chairs attend Council meetings to maintain continuity and continued communication, as well as provide guidance to the current Co-chairs or other committee leads.

**EREN Council:** *Phil Riddle, Eric Ekholm, Rebecca Towery, Chad Green, Tiffany Hinton, Amanda Schutz, and Jennifer Cassata*

The Council convenes monthly to (a) ensure the alignment of committee plans and activities, (b) oversee membership outreach/recruitment, and (c) support host sites in preparation for the biannual meetings.  The Council is composed of the current co-chairs, past co-chairs, and committee leads.  One current co-chair shall be a voting member with the other serving as ex officio, only voting in case of a tie.

## Committees

**Advocacy Committee**: *Tiffany Hinton (lead), Ryan Tyler, and Clint Page*

The advocacy committee researches, monitors, and provides feedback on state policies and practices.

**Communication and Publicity Committee**: *Amanda Schutz (lead), Phil Riddle, Chad Green, Helen Whitehurst, Allison Bock, and Jennifer Whitson*

The communication and publicity committee manages the EREN website, discussion lists, social media presence, job announcements, publicity of upcoming meetings, membership recruitment, etc.

**Program Planning Committee:** *Jennifer Cassata (lead), Rebecca Towery (lead), Tim Neall, Tina Constantine, Amber Ebi, and Angi Green*

The program planning committee organizes biannual meetings, online consultations, and lunch-and-learns.